/* cmdline.h Copyright(c) under GPL 2003-2011 Sean Dwyer <ewe2@users.sourceforge.net> */

/* $Id$ */
/* File autogenerated by gengetopt version 2.4 and then massively fiddled with */


#ifndef _cmdline_h
#define _cmdline_h

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

// take care of getopt dependencies
#ifdef HAVE_GETOPT_LONG
    #include <getopt.h>   
#endif

#ifdef NEED_INCLUDED_GETOPT
    #include "getopt.h"
#endif

struct gengetopt_args_info {
  double correlation_arg;	/* optional correlation (default=no).  */
  int dmy_arg1;	/* day month year (Gregorian).  */
  int dmy_arg2;
  int dmy_arg3;
  double julian_arg;	/* julian day number.  */
  int longcount_arg1;	/* long count.  */
  int longcount_arg2;
  int longcount_arg3;
  int longcount_arg4;
  int longcount_arg5;
  char *format_arg;

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int correlation_given ;	/* Whether correlation was given.  */
  int dmy_given ;	/* Whether dmy was given.  */
  int julian_given ;	/* Whether julian was given.  */
  int longcount_given ;	/* Whether longcount was given.  */
  int format_given; /* Whether format was given. */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#endif /* _cmdline_h */
