/* cmdline.h Copyright(c) under GPL 2003-2007 Sean Dwyer <ewe2@users.sourceforge.net> */

/* $Id: cmdline.h 20 2010-09-22 07:18:19Z ewe2 $ */
/* File autogenerated by gengetopt version 2.4 and then massively fiddled with */


#ifndef _cmdline_h
#define _cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

// take care of getopt dependencies
#ifdef HAVE_GETOPT_LONG
    #include <getopt.h>   
#endif

#ifdef NEED_INCLUDED_GETOPT
    #include "getopt.h"
#endif

struct gengetopt_args_info {
  int parseable_flag;	/* program-parseable output (default=off).  */
  int gmt_flag;	/* use gmt correlation (default=off).  */
  double correlation_arg;	/* optional correlation (default=no).  */
  int dmy_arg1;	/* day month year (Gregorian).  */
  int dmy_arg2;
  int dmy_arg3;
  double julian_arg;	/* julian day number.  */
  int longcount_arg1;	/* long count.  */
  int longcount_arg2;
  int longcount_arg3;
  int longcount_arg4;
  int longcount_arg5;
  char *format_arg;

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int parseable_given ;	/* Whether parseable was given.  */
  int gmt_given ;	/* Whether gmt was given.  */
  int correlation_given ;	/* Whether correlation was given.  */
  int dmy_given ;	/* Whether dmy was given.  */
  int julian_given ;	/* Whether julian was given.  */
  int longcount_given ;	/* Whether longcount was given.  */
  int format_given; /* Whether format was given. */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* _cmdline_h */
