#!/bin/sh
# db2html processor, asciidoc version.
# mdate.xml target is made by Makefile rule.
#asciidoc -a toc -b docbook mdate.txt
xsltproc -nonet --stringparam html.stylesheet ./docbook-xsl.css docbook-xsl/xhtml.xsl mdate.xml > mdate.html
